services:
  infofront:
    build:
      context: ./infoFront  # Убедитесь, что этот путь правильный
      dockerfile: Dockerfile  # Убедитесь, что Dockerfile находится в этой папке
    networks:
      - app-network

  backend:
    build:
      context: ./IntotecsBackendRrs  # Путь к вашему бэкенду
      dockerfile: Dockerfile  # Убедитесь, что Dockerfile находится в этой папке
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Подключаем конфигурацию Nginx
    ports:
      - "80:80"  # Открываем порт 80 для внешнего доступа
    depends_on:
      - infofront
      - backend
    networks:
      - app-network

networks:
  app-network: